services:
  server:
    environment:
      APP_ENV: development
      PUBLIC_ORIGIN: http://localhost:8080
    ports: ["127.0.0.1:8081:8080"]
  worker:
    environment:
      APP_ENV: development
      PUBLIC_ORIGIN: http://localhost:8080
