ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS office_location text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo text NOT NULL DEFAULT '';
